### ISSUE TITLE
Switches Rotation Mode but doesnt convert animation

### ISSUE THREAD

**Issue by lucianomunoz** [L0Lock/convertRotationMode#26]
Hey, I'm on blender 3.6 on a mac, and seems to switch the rotation mode but it doesn't convert the animation to that said rotation.

The copy global transforms addon is on.

**Comment by L0Lock** [comment]
Hi!  
Sorry for the delayed answer, got a busy week at work :) Got a new procedure to cycle through keyframes by making use of the ability to key down the rotation mode, which is more performant and robust, and remove that issue and another one. Just need to polish it a bit.

**Comment by L0Lock** [comment]
Hi!

The bug should have been fixed and the addon overall enhanced with a bunch of new options (see addon'; s prefs_

Please try v1.2.4 and let me know how it goes or if you have any suggestion:
[convert_Rotation_Mode.py](https://raw.githubusercontent.com/L0Lock/convertRotationMode/6c1bd70afa079131c8183183f6a5a60d2c54e037/convert_Rotation_Mode.py)
